BANDWIDTH = 1.75e6
SAMPLE_RATE = 5e6
RX_FREQ = 315e6
BUFFER_LENGTH = 4096
SAMPLES_PER_READ = 128
RX_GAIN = 45
MOVING_AVERAGE_RATIO = 0.125

# in keyboard is_pressed it re-prints if the function won't sleep
CANCEL_REPRINT_SLEEP_TIME = 0.12

# runtime booleans
BOOL_RUN = True
BOOL_MAX_HOLD = False
BOOL_CLEAR_PLOT = False
BOOL_MOOVING_AVERAGE = False
BOOL_LOG_SCALE = False
BOOL_SNEAK_FROM_LO = False
